<?php

namespace GS\BackOfficeBundle\Repository;


/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends \Doctrine\ORM\EntityRepository
{
    public function nom($rech){
        $query = DocumentRepository::createQueryBuilder('d')
         ->where('d.nom like :nom')
         ->setParameter('nom','%'.$rech.'%')
         ->getQuery();
        return $query->getResult();
    }

    public function triDate($id){
        $query = DocumentRepository::createQueryBuilder('d')
            ->join('d.idEns' , 'e')
            ->addSelect('e')
            ->where('e.id = :id')
            ->orderBy('d.date','desc')
            ->setParameter('id',$id)
            ->getQuery();
       return $query->getResult();
    }

    public function tri($id){
        $query = DocumentRepository::createQueryBuilder('d')
            ->join('d.idClasse' , 'c')
            ->addSelect('c')
            ->where('c.id = :id')
            ->orderBy('d.date','desc')
            ->setParameter('id',$id)
            ->getQuery();
        return $query->getResult();
    }
}
