<?php

namespace GS\BackOfficeBundle\Repository;

/**
 * EcoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcoleRepository extends \Doctrine\ORM\EntityRepository
{
    public function alphaNum($annuler){

        $query = $this->getEntityManager()->createQuery('select e from BackOfficeBundle:Ecole e 
where e.annuler = :annuler ORDER BY e.username')
            ->setParameters(array('annuler'=>$annuler));
        return $query->getResult();
    }

    public function usernameP($username){
        $query = EcoleRepository::createQueryBuilder('e')
            ->where('e.adresse like :username')
            ->setParameter('username','%'.$username.'%')
            ->getQuery();
        return $query->getResult();
    }

    public function khraa($adresse){
        $query = $this->getEntityManager()->createQuery('select e from BackOfficeBundle:Ecole e 
where e.adresse LIKE :adresse')
            ->setParameter('telephone','%'.$adresse.'%')
            ->getQuery();
        return $query->getResult();

    }
}
