<?php

namespace GS\BackOfficeBundle\Repository;

/**
 * EnsMatClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnsMatClasseRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechClasse($classe){
        $query = EnsMatClasseRepository::createQueryBuilder('m')
            ->join('m.classeId','c')
            ->addSelect('c')
            ->where('c.niveau = :niveau')
            ->setParameter('niveau',$classe)
            ->getQuery();
        return $query->getResult();
    }

    public function nomClasse($nom,$classe){
        $query = EnsMatClasseRepository::createQueryBuilder('m')
            ->join('m.classeId','c')
            ->join('m.matId','mat')
            ->addSelect('c')
            ->where('c.niveau = :niveau')
            ->addSelect('mat')
            ->where('mat.nom = :nom')
            ->setParameters(array('niveau'=>$classe,'nom'=>$nom))
            ->getQuery();
        return $query->getResult();
    }
}
