<?php

namespace GS\BackOfficeBundle\Repository;

/**
 * MatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByNiveau($niv){
        $query = MatiereRepository::createQueryBuilder('m')
            ->where('m.niveau = :niveau')
            ->setParameter('niveau',$niv)
            ->getQuery();
       return $query->getResult();
    }


    public function alphaNum($annuler,$id){
        $query = $this->getEntityManager()->createQuery('select e from BackOfficeBundle:Matiere e 
where e.idEcole = (select ec from BackOfficeBundle:Ecole ec where ec.id = :id) AND e.annuler = :annuler ORDER BY e.nom')
            ->setParameters(array('id'=>$id,'annuler'=>$annuler));
        return $query->getResult();
    }

    public function rechNom($search){
        $query = MatiereRepository::createQueryBuilder('e')
            ->where('e.nom like :nom')
            ->setParameter('nom','%'.$search.'%')
            ->getQuery();
        return $query->getResult();
    }

    public function nomClasse($nom,$classe,$id){
              $query = $this->getEntityManager()->createQuery('select e from BackOfficeBundle:Matiere e 
where e.idEcole = (select ec from BackOfficeBundle:Ecole ec where ec.id = :id) AND e.nom LIKE :nom AND e.niveau = :niveau')
            ->setParameters(array('nom'=>'%'.$nom.'%','niveau'=>$classe,'id'=>$id))
            ;
        return $query->getResult();
    }

}
