<?php

namespace GS\BackOfficeBundle\Repository;

/**
 * SupAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupAdminRepository extends \Doctrine\ORM\EntityRepository
{
}
